import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F6F7FB',
  },
  screen: {
    flex: 1,
    backgroundColor: '#F6F7FB',
  },
  container: {
    padding: 22,
    paddingBottom: 46,
  },
  transacoesContainer: {
    flex: 1,
    padding: 22,
    paddingBottom: 0,
  },
  listaTransacoes: {
    flex: 1,
  },
  pageEyebrow: {
    fontSize: 12,
    fontWeight: '800',
    color: '#6B7280',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  pageTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 8,
    letterSpacing: -0.7,
  },
  pageSubtitle: {
    fontSize: 15,
    color: '#6B7280',
    marginBottom: 22,
    lineHeight: 22,
  },
  heroCard: {
    backgroundColor: '#111827',
    borderRadius: 28,
    padding: 22,
    marginBottom: 16,
    shadowColor: '#111827',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  heroLabel: {
    color: '#D1D5DB',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroValue: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: -1.2,
  },
  heroText: {
    color: '#D1D5DB',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  fieldBox: {
    marginBottom: 15,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#111827',
    shadowColor: '#111827',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  pickerBox: {
    marginBottom: 15,
  },
  filtersCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
  },
  filterRow: {
    gap: 14,
  },
  filterBox: {
    width: '100%',
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  pickerInput: {
    height: 56,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 18,
    justifyContent: 'center',
    shadowColor: '#111827',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  picker: {
    width: '100%',
    height: 56,
    color: '#111827',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 12,
    fontSize: 15,
  },
  primaryButton: {
    backgroundColor: '#111827',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#111827',
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
    letterSpacing: 0.2,
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 12,
  },
  secondaryButtonText: {
    color: '#111827',
    fontWeight: '900',
    fontSize: 15,
    letterSpacing: 0.2,
  },
  errorText: {
    color: '#991B1B',
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  syncBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 16,
    marginBottom: 16,
  },
  syncPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#EEF2FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 10,
  },
  syncPillText: {
    color: '#3730A3',
    fontSize: 11,
    fontWeight: '900',
  },
  syncTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 4,
  },
  syncText: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 19,
  },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  loadingText: {
    color: '#6B7280',
    fontWeight: '700',
  },
  summaryGrid: {
    gap: 12,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#111827',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  summaryTitle: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '800',
  },
  summaryValue: {
    fontSize: 28,
    color: '#111827',
    fontWeight: '900',
    marginVertical: 6,
    letterSpacing: -0.7,
  },
  summaryDescription: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  listContent: {
    paddingBottom: 130,
  },
  transactionItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 17,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  transactionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  typeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
    marginBottom: 12,
  },
  badgeEntrada: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  badgeSaida: {
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#111827',
  },
  transactionValue: {
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  textEntrada: {
    color: '#059669',
  },
  textSaida: {
    color: '#E11D48',
  },
  transactionTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 5,
  },
  transactionMeta: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '700',
  },
  transactionDate: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 7,
    fontWeight: '700',
  },
  emptyText: {
    textAlign: 'center',
    color: '#6B7280',
    marginTop: 34,
    fontWeight: '700',
  },
  centerBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#F6F7FB',
  },
  detailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  detailValue: {
    fontSize: 32,
    fontWeight: '900',
    marginBottom: 18,
    letterSpacing: -0.8,
  },
  detailLine: {
    fontSize: 15,
    color: '#374151',
    marginBottom: 10,
    lineHeight: 21,
  },
  drawerContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  drawerHeader: {
    padding: 22,
    backgroundColor: '#111827',
    marginBottom: 12,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
  },
  drawerAppName: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: '900',
    marginBottom: 16,
    letterSpacing: -0.5,
  },
  drawerUser: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  drawerEmail: {
    color: '#D1D5DB',
    fontSize: 13,
    marginTop: 4,
  },
  appHeader: {
    height: 56,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  appHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  appHeaderButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appHeaderHamburger: {
    fontSize: 22,
    color: '#111827',
  },
  drawerPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 280,
    backgroundColor: '#FFFFFF',
    zIndex: 100,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 10, height: 0 },
    elevation: 20,
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 99,
  },
  drawerNavItem: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 14,
    marginHorizontal: 10,
    marginBottom: 4,
  },
  drawerNavItemActive: {
    backgroundColor: '#EEF2FF',
  },
  drawerNavItemText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  drawerNavItemTextActive: {
    color: '#111827',
  },
  toggleBox: {
    marginBottom: 15,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 10,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  toggleButtonActiveEntrada: {
    backgroundColor: '#ECFDF5',
    borderColor: '#059669',
  },
  toggleButtonActiveSaida: {
    backgroundColor: '#FFF1F2',
    borderColor: '#E11D48',
  },
  toggleButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  toggleButtonTextActive: {
    color: '#111827',
  },
  welcomeContainer: {
    padding: 28,
    paddingBottom: 46,
    flexGrow: 1,
    justifyContent: 'center',
  },
  welcomeHero: {
    marginBottom: 36,
  },
  welcomeAppName: {
    fontSize: 42,
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -1.5,
    marginBottom: 10,
  },
  welcomeTagline: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 24,
  },
  voltarButton: {
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  voltarText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
});
